name: Check Dart SDK updates

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

env:
  USER: Github Actions <github-actions@users.noreply.github.com>
  COMMENT: Update Dart SDK

jobs:
  check-dart-updates:
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: dnf -y install git python rpmdevtools

      - name: Retrieve latest Dart SDK version
        run: echo "dart_version=$(python dart-latest-version.py)" >> $GITHUB_ENV

      - name: Bump Dart SDK version in the spec file
        run: rpmdev-bumpspec -D -u "$USER" -c "$COMMENT" dart.spec -n "${{ env.dart_version }}"

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Dart SDK to v${{ env.dart_version }}
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
